name: Baseline Package & Report
description: Stage/manifest/zip/report (placeholder)
inputs: {}
outputs: {}
runs:
  using: 'composite'
  steps:
    - id: ok
      shell: bash
      run: echo "Baseline package: OK (placeholder)"
