name: Baseline Client Daily (reusable)
on:
  workflow_call:
    inputs:
      run_domain_hook:
        required: false
        type: boolean
        default: true
    secrets:
      COGNOS_PUSH_TOKEN:
        required: true

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Baseline validate (placeholder)
        shell: bash
        run: |
          echo "Baseline validate: OK (placeholder)"

      - name: Baseline package & report (placeholder)
        shell: bash
        run: |
          echo "Baseline package: OK (placeholder)"
